# Generated by Django 2.1.2 on 2018-11-01 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membre', '0053_auto_20181101_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recette', models.PositiveIntegerField(null=True, verbose_name='Recette')),
                ('prelevement', models.PositiveIntegerField(null=True, verbose_name='Prélevement')),
                ('creance', models.PositiveIntegerField(verbose_name='Créance dûe')),
                ('date_recette', models.DateTimeField(auto_now_add=True, verbose_name='Date de la recette')),
                ('entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.EntrepriseCommerciale', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Recette Effectuée',
                'verbose_name_plural': 'Recettes Effectuées',
                'ordering': ['entreprise', '-date_recette'],
            },
        ),
    ]
