# Generated by Django 2.1.2 on 2018-11-01 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0054_auto_20181101_0148'),
        ('recette', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetteMensuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recette', models.PositiveIntegerField(null=True, verbose_name='Recette')),
                ('prelevement', models.PositiveIntegerField(null=True, verbose_name='Prélevement')),
                ('creance', models.PositiveIntegerField(verbose_name='Créance dûe')),
                ('mois', models.CharField(choices=[('Janvier', 'Janvier'), ('Reserver', 'Février'), ('Mars', 'Mars'), ('En Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre')], max_length=50, null=True, verbose_name='Mois')),
                ('date_recette', models.DateTimeField(auto_now_add=True, verbose_name='Date complète de la recette')),
                ('entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.EntrepriseCommerciale', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Recette Effectuée',
                'verbose_name_plural': 'Recettes Effectuées',
                'ordering': ['entreprise', '-date_recette'],
            },
        ),
    ]
