# Generated by Django 2.1.2 on 2018-11-01 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0055_auto_20181101_1135'),
        ('recette', '0002_recettemensuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetteAnnuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recette', models.PositiveIntegerField(null=True, verbose_name='Recette')),
                ('prelevement', models.PositiveIntegerField(null=True, verbose_name='Prélevement')),
                ('creance', models.PositiveIntegerField(verbose_name='Créance dûe')),
                ('date_recette', models.DateTimeField(auto_now_add=True, verbose_name='Date ')),
                ('entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.EntrepriseCommerciale', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Recette Annuelle',
                'verbose_name_plural': 'Recettes Annuelles',
                'ordering': ['entreprise', '-date_recette'],
            },
        ),
        migrations.AlterModelOptions(
            name='recette',
            options={'ordering': ['entreprise', '-date_recette'], 'verbose_name': 'Recette Journalière', 'verbose_name_plural': 'Recettes Journalières'},
        ),
        migrations.AlterModelOptions(
            name='recettemensuel',
            options={'ordering': ['entreprise', '-date_recette'], 'verbose_name': 'Recette Mensuel', 'verbose_name_plural': 'Recettes Mensuels'},
        ),
        migrations.AlterField(
            model_name='recettemensuel',
            name='date_recette',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date '),
        ),
        migrations.AlterField(
            model_name='recettemensuel',
            name='mois',
            field=models.CharField(choices=[('Janvier', 'Janvier'), ('Reserver', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre')], max_length=50, null=True, verbose_name='Mois'),
        ),
    ]
