# Generated by Django 2.1.1 on 2018-10-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionBesoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('besoin', models.CharField(max_length=80, verbose_name='Besoin')),
            ],
        ),
    ]
