# Generated by Django 2.1.1 on 2018-10-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_expressionbesoin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expressionbesoin',
            options={'verbose_name': 'Besoins Humains Gérés'},
        ),
    ]
