# Generated by Django 2.1.1 on 2018-10-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20181020_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressionbesoin',
            name='image_illustratif',
            field=models.ImageField(null=True, upload_to='besoins/', verbose_name='image associé'),
        ),
    ]
