# Generated by Django 2.1.1 on 2018-10-20 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20181020_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produits ou Services'},
        ),
        
    ]
