# Generated by Django 2.1.1 on 2018-10-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_productitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpécificationBesoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spécification', models.CharField(max_length=80, verbose_name='Spécification')),
                ('image_illustratif', models.ImageField(null=True, upload_to='specifications_besoins/', verbose_name='image associé')),
                ('besoin_fondamental', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.ExpressionBesoin')),
            ],
            options={
                'verbose_name': 'Spécifiaction des Besoins',
            },
        ),
    ]
