# Generated by Django 2.1.1 on 2018-10-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0044_auto_20181024_1858'),
        ('ecommerce', '0014_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'article")),
                ('code_article', models.CharField(max_length=100, verbose_name="Code de l'article")),
                ('marque', models.CharField(max_length=50, null=True)),
                ('modele', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('image_produit', models.ImageField(null=True, upload_to='produits/', verbose_name='Image')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('categorie_besoin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.SpécificationBesoin')),
                ('vendeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.EntrepriseCommerciale')),
            ],
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='vendeur',
        ),
        migrations.DeleteModel(
            name='ProductItem',
        ),
    ]
