# Generated by Django 2.1.1 on 2018-10-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_auto_20181024_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='code_article',
            field=models.CharField(max_length=100, unique=True, verbose_name="Code de l'article"),
        ),
    ]
