# Generated by Django 2.1.2 on 2018-11-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_auto_20181109_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='code_article',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name="Code de l'article"),
        ),
    ]
