# Generated by Django 2.1.2 on 2018-11-15 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_auto_20181109_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=100, null=True, verbose_name='Nom de la Catégorie')),
                ('image_categorie', models.ImageField(blank=True, null=True, upload_to='categorie/', verbose_name='Image de la Catégorie')),
                ('specification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.SpécificationBesoin')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
    ]
