# Generated by Django 2.1.2 on 2018-11-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_produit_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.PositiveIntegerField(null=True, verbose_name="Prix de l'article"),
        ),
    ]
