# Generated by Django 2.1.2 on 2018-11-18 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_produit_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie_besoin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.SpécificationBesoin', verbose_name='Spécification'),
        ),
    ]
