# Generated by Django 2.1.2 on 2019-07-28 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0093_auto_20190728_1241'),
        ('ecommerce', '0024_produit_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitTroc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'article")),
                ('code_article', models.CharField(blank=True, max_length=100, unique=True, verbose_name="Code de l'article")),
                ('prix', models.PositiveIntegerField(null=True, verbose_name="Prix de l'article")),
                ('marque', models.CharField(blank=True, max_length=50, null=True)),
                ('modele', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_produit', models.ImageField(null=True, upload_to='produits/', verbose_name='Image')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=True)),
                ('vendeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.ConsommateurParticulier')),
            ],
            options={
                'verbose_name': 'Article Troqué',
                'verbose_name_plural': 'Articles Troqués',
            },
        ),
    ]
