# Generated by Django 2.1.2 on 2019-07-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_produittroc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produittroc',
            name='image_produit',
            field=models.ImageField(null=True, upload_to='produitsTroques/', verbose_name='Image'),
        ),
    ]
