# Generated by Django 2.1.1 on 2018-09-26 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OctroiCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epounds_disponible', models.PositiveIntegerField(null=True, verbose_name='Unités e-pounds disponibles')),
                ('montant_pret', models.PositiveIntegerField(null=True, verbose_name='Montant du prêt')),
                ('montant_prelever_sur_beta', models.PositiveIntegerField(null=True, verbose_name='Montant à prélever sur le compte bêta')),
                ('delais_rembousement', models.PositiveIntegerField(null=True, verbose_name='Délais de remboursement(nombre de mois)')),
                ('mot_de_passe', models.CharField(max_length=100, null=True, verbose_name='Mot de passe')),
                ('date_butoir_payement', models.DateTimeField(editable=False, null=True, verbose_name='Date butoir du payement')),
                ('beneficiaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='membre.EntrepriseCommerciale', verbose_name='Bénéficiaire')),
                ('operateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Opérateur')),
            ],
            options={
                'verbose_name': 'Octroi de Crédit',
                'verbose_name_plural': 'Octrois de Crédits',
            },
        ),
    ]
