# Generated by Django 2.1.1 on 2018-10-06 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('octroi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='octroicredit',
            name='operateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='octroyeur', to=settings.AUTH_USER_MODEL, verbose_name='Opérateur'),
        ),
    ]
