# Generated by Django 2.1.1 on 2018-10-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octroi', '0002_auto_20181006_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='octroicredit',
            name='montant_prelever_sur_grenier',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='Montant prélever sur le compte grenier'),
        ),
        migrations.AlterField(
            model_name='octroicredit',
            name='montant_prelever_sur_beta',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='Montant à prélever sur le compte bêta'),
        ),
    ]
