# Generated by Django 2.1.1 on 2018-10-27 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('octroi', '0003_auto_20181027_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='octroicredit',
            name='epounds_disponible',
        ),
        migrations.AddField(
            model_name='octroicredit',
            name='date_octroi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'octroi du crédit"),
            preserve_default=False,
        ),
    ]
