# Generated by Django 2.1.1 on 2018-10-27 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0048_auto_20181027_1510'),
        ('octroi', '0004_auto_20181027_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField(null=True, verbose_name='Montant remboursé')),
                ('date_remboursement', models.DateTimeField(auto_now_add=True, verbose_name='Date de rembboursement')),
                ('debiteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='membre.EntrepriseCommerciale', verbose_name='Débiteur')),
            ],
            options={
                'verbose_name': 'Remboursement',
            },
        ),
        migrations.AddField(
            model_name='octroicredit',
            name='reboursser',
            field=models.BooleanField(default=False, verbose_name='Octroi rembourser'),
        ),
        migrations.AddField(
            model_name='octroicredit',
            name='reste',
            field=models.PositiveIntegerField(null=True, verbose_name='Reste à rembourser'),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='octroi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='octroi.OctroiCredit', verbose_name='Octroi associé'),
        ),
    ]
