# Generated by Django 2.1.1 on 2018-10-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octroi', '0005_auto_20181027_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remboursement',
            name='debiteur',
        ),
        migrations.RemoveField(
            model_name='remboursement',
            name='octroi',
        ),
        migrations.DeleteModel(
            name='Remboursement',
        ),
    ]
