# Generated by Django 2.1.1 on 2018-10-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncommercialcomsommateur',
            name='solde_apres_transaction',
            field=models.PositiveIntegerField(null=True, verbose_name='Solde après transaction'),
        ),
        migrations.AddField(
            model_name='transactionintercomsommateur',
            name='solde_apres_transaction',
            field=models.PositiveIntegerField(null=True, verbose_name='Solde après transaction'),
        ),
    ]
