# Generated by Django 2.1.1 on 2018-10-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20181014_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversiontrader',
            name='consommateur',
        ),
        migrations.RemoveField(
            model_name='conversiontrader',
            name='trader',
        ),
        migrations.RemoveField(
            model_name='reconversiontrader',
            name='consommateur',
        ),
        migrations.RemoveField(
            model_name='reconversiontrader',
            name='trader',
        ),
        migrations.RemoveField(
            model_name='transactioncommercialcomsommateur',
            name='envoyeur',
        ),
        migrations.RemoveField(
            model_name='transactioncommercialcomsommateur',
            name='receveur',
        ),
        migrations.RemoveField(
            model_name='transactionintercomsommateur',
            name='envoyeur',
        ),
        migrations.RemoveField(
            model_name='transactionintercomsommateur',
            name='receveur',
        ),
        migrations.DeleteModel(
            name='ConversionTrader',
        ),
        migrations.DeleteModel(
            name='ReconversionTrader',
        ),
        migrations.DeleteModel(
            name='TransactionCommercialComsommateur',
        ),
        migrations.DeleteModel(
            name='TransactionInterComsommateur',
        ),
    ]
