# Generated by Django 2.1.1 on 2018-09-26 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconversionConsommateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epounds_disponible', models.PositiveIntegerField(null=True, verbose_name='Unités e-pounds disponibles')),
                ('epounds_a_reconvertir', models.PositiveIntegerField(null=True, verbose_name='Unités e-pounds à reconvertir')),
                ('montant_a_prelever', models.PositiveIntegerField(null=True, verbose_name='e-pounds à prélever')),
                ('montant_en_cfa', models.PositiveIntegerField(null=True, verbose_name='Montant rendu en cfa')),
                ('mot_de_passe', models.CharField(max_length=100, null=True, verbose_name='Mot de passe')),
                ('beneficiaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='membre.Consommateur', verbose_name='Bénéficiaire')),
                ('operateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Opérateur')),
            ],
            options={
                'verbose_name': "Reconversion d'un Consommateur",
                'verbose_name_plural': 'Reconversions des Consommateurs',
            },
        ),
        migrations.CreateModel(
            name='ReconversionEntrepriseCommerciale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epounds_disponible', models.PositiveIntegerField(null=True, verbose_name='Unités e-pounds disponibles')),
                ('epounds_a_reconvertir', models.PositiveIntegerField(null=True, verbose_name='Unités e-pounds à reconvertir')),
                ('montant_a_prelever', models.PositiveIntegerField(null=True, verbose_name='e-pounds à prélever')),
                ('montant_en_cfa', models.PositiveIntegerField(null=True, verbose_name='Montant rendu en cfa')),
                ('montant_virer_sur_compte_conso', models.PositiveIntegerField(null=True, verbose_name='e-pounds à transférer sur le compte e-c')),
                ('mot_de_passe', models.CharField(max_length=100, null=True, verbose_name='Mot de passe')),
                ('beneficiaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='membre.EntrepriseCommerciale', verbose_name='Bénéficiaire')),
                ('operateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Opérateur')),
            ],
            options={
                'verbose_name': "Reconversion d'unités d'entreprise",
                'verbose_name_plural': "Reconversions d'unités d'entreprises",
            },
        ),
    ]
