# Generated by Django 2.1.1 on 2018-10-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconversion', '0004_auto_20181006_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconversionentreprisecommerciale',
            name='epounds_a_reconvertir',
            field=models.PositiveIntegerField(null=True, verbose_name='Prélevement'),
        ),
        migrations.AlterField(
            model_name='reconversionentreprisecommerciale',
            name='epounds_disponible',
            field=models.PositiveIntegerField(null=True, verbose_name='Recette'),
        ),
        migrations.AlterField(
            model_name='reconversionentreprisecommerciale',
            name='montant_en_cfa',
            field=models.PositiveIntegerField(null=True, verbose_name='Réglement'),
        ),
    ]
