# Generated by Django 2.1.1 on 2018-09-27 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epounds_retrancher', models.PositiveIntegerField(default=0, verbose_name='epounds retranchés')),
                ('voulume_convertible', models.PositiveIntegerField(default=0, verbose_name='epounds convertibles en monnaie local')),
                ('volume_retransferer', models.PositiveIntegerField(default=0, verbose_name='epounds retransferés sur le comptes e-c')),
                ('entreprise_associer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='membre.EntrepriseCommerciale', verbose_name='Entreprise associée')),
            ],
        ),
        migrations.CreateModel(
            name='CreanceTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_epounds', models.PositiveIntegerField(default=0)),
                ('epounds_retrancher', models.PositiveIntegerField(default=0, verbose_name='epounds retranchés')),
                ('voulume_convertible', models.PositiveIntegerField(default=0, verbose_name='epounds convertibles en monnaie local')),
                ('volume_retransferer', models.PositiveIntegerField(default=0, verbose_name='epounds retransferés sur les comptes e-c')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
