# Generated by Django 2.1.1 on 2018-10-01 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creance',
            name='entreprise_associer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.EntrepriseCommerciale', verbose_name='Entreprise associée'),
        ),
    ]
