# Generated by Django 2.1.1 on 2018-10-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20181027_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creancetotal',
            name='epounds_retrancher',
            field=models.PositiveIntegerField(default=0, verbose_name='Prélevement reconversion (5%)'),
        ),
        migrations.AlterField(
            model_name='creancetotal',
            name='voulume_convertible',
            field=models.PositiveIntegerField(default=0, verbose_name='Reconversion (70%)'),
        ),
    ]
