# Generated by Django 2.1.1 on 2018-10-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20181027_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creancetotal',
            name='volume_retransferer',
            field=models.PositiveIntegerField(default=0, verbose_name='epounds retransferés sur les comptes e-c (30%)'),
        ),
    ]
