# Generated by Django 2.1.1 on 2018-10-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20181027_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreanceMonetaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumul_bonification', models.PositiveIntegerField(default=0, verbose_name='Cumul du solde des comptes consommateurs')),
                ('compte_beta', models.PositiveIntegerField(default=0, verbose_name='Solde du compte bêta')),
                ('compte_grenier', models.PositiveIntegerField(default=0, verbose_name='Solde du compte grenier')),
                ('solde', models.PositiveIntegerField(default=0, verbose_name='Solde')),
            ],
            options={
                'verbose_name': 'Créance Monétaire',
                'verbose_name_plural': 'Créance Monétaire',
            },
        ),
    ]
