# Generated by Django 2.1.1 on 2018-10-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_creancemonetaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creancemonetaire',
            name='cumul_bonification',
            field=models.PositiveIntegerField(default=0, verbose_name='Cumul des bonnifications (50%)'),
        ),
    ]
