# Generated by Django 2.1.1 on 2018-10-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_indicedeconversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicedeconversion',
            options={'verbose_name': 'Indice de Conversion', 'verbose_name_plural': 'Indice de Conversion'},
        ),
        migrations.AddField(
            model_name='indicedeconversion',
            name='taux',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Indice'),
        ),
        migrations.AddField(
            model_name='indicedeconversion',
            name='total_reconversion',
            field=models.PositiveIntegerField(null=True, verbose_name='e-pounds achetés'),
        ),
    ]
