# Generated by Django 2.1.1 on 2018-10-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20181029_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicedeconversion',
            name='total_acheter',
            field=models.PositiveIntegerField(null=True, verbose_name='e-pounds achetés'),
        ),
        migrations.AlterField(
            model_name='indicedeconversion',
            name='total_reconversion',
            field=models.PositiveIntegerField(null=True, verbose_name='e-pounds reconverties en monnaie locale'),
        ),
    ]
