# Generated by Django 2.1.2 on 2018-11-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20181029_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsommationMensuelMoyenneConsommateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epound_utiliser', models.PositiveIntegerField(null=True, verbose_name='cumul des unités e-pounds utilisées à la consommation')),
                ('date', models.DateField(null=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Consommation mensuel moyenne des Consommateurs',
                'verbose_name_plural': 'Consommation mensuel moyenne des Consommateurs',
            },
        ),
        migrations.CreateModel(
            name='ConsommationMensuelMoyenneConsommateurActuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epound_utiliser', models.PositiveIntegerField(null=True, verbose_name='cumul des unités e-pounds utilisées à la consommation')),
                ('date_debut_consommation', models.DateField(null=True, verbose_name='Début de consommation')),
            ],
            options={
                'verbose_name': 'Consommation mensuel moyenne actuel des Consommateurs',
                'verbose_name_plural': 'Consommation mensuel moyenne actuel des Consommateurs',
            },
        ),
        migrations.CreateModel(
            name='ConsommationMensuelMoyenneVendeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epound_utiliser', models.PositiveIntegerField(null=True, verbose_name='cumul des unités e-pounds utilisées à la consommation')),
                ('date', models.DateField(null=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Consommation mensuel moyenne des Vendeurs',
                'verbose_name_plural': 'Consommation mensuel moyenne des Vendeurs',
            },
        ),
        migrations.CreateModel(
            name='ConsommationMensuelMoyenneVendeurActuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epound_utiliser', models.PositiveIntegerField(null=True, verbose_name='cumul des unités e-pounds utilisées à la consommation')),
                ('date_debut_consommation', models.DateField(null=True, verbose_name='Début de consommation')),
            ],
            options={
                'verbose_name': 'Consommation mensuel moyenne des Vendeurs',
                'verbose_name_plural': 'Consommation mensuel moyenne des Vendeurs',
            },
        ),
    ]
