# Generated by Django 2.1.2 on 2018-11-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_consommationmensuelmoyenneconsommateur_consommationmensuelmoyenneconsommateuractuel_consommationmens'),
    ]

    operations = [
        migrations.CreateModel(
            name='TauxAbsorbtionGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epound_detenus', models.PositiveIntegerField(null=True, verbose_name='unités e-ponds détenues par l’ensemble des consommateurs')),
                ('epound_consommer', models.PositiveIntegerField(null=True, verbose_name='unités e-pounds utilisées à la consommation au cours du mois')),
            ],
        ),
        migrations.CreateModel(
            name='TauxAbsorbtionGlobalMensuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epound_detenus', models.PositiveIntegerField(null=True, verbose_name='unités e-ponds détenues par l’ensemble des consommateurs')),
                ('epound_consommer', models.PositiveIntegerField(null=True, verbose_name='unités e-pounds utilisées à la consommation au cours du mois')),
                ('mois', models.DateField(null=True, verbose_name='Mois')),
            ],
        ),
    ]
