# Generated by Django 2.1.2 on 2018-11-05 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_tauxabsorbtionglobal_tauxabsorbtionglobalmensuel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tauxabsorbtionglobal',
            options={'verbose_name': "Taux d'absorbtion global", 'verbose_name_plural': "Taux d'absorbtion global"},
        ),
        migrations.AlterModelOptions(
            name='tauxabsorbtionglobalmensuel',
            options={'verbose_name': "Taux d'absorbtion mensuel", 'verbose_name_plural': "Taux d'absorbtion mensuel"},
        ),
    ]
