# Generated by Django 2.1.2 on 2018-11-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20181105_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='tauxabsorbtionglobal',
            name='mois',
            field=models.CharField(max_length=30, null=True, verbose_name='Mois'),
        ),
        migrations.AddField(
            model_name='tauxabsorbtionglobalmensuel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tauxabsorbtionglobalmensuel',
            name='mois',
            field=models.CharField(max_length=30, null=True, verbose_name='Mois'),
        ),
    ]
