# Generated by Django 2.1.2 on 2018-11-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20181107_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consommationmensuelmoyennevendeuractuel',
            options={'verbose_name': 'Consommation mensuel moyenne actuel des Vendeurs', 'verbose_name_plural': 'Consommation mensuel moyenne actuel des Vendeurs'},
        ),
        migrations.AddField(
            model_name='consommationmensuelmoyenneconsommateur',
            name='nombre_mois',
            field=models.PositiveIntegerField(null=True, verbose_name='Nombre de mois'),
        ),
        migrations.AddField(
            model_name='consommationmensuelmoyennevendeur',
            name='nombre_mois',
            field=models.PositiveIntegerField(null=True, verbose_name='Nombre de mois'),
        ),
        migrations.AlterField(
            model_name='consommationmensuelmoyenneconsommateur',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='consommationmensuelmoyennevendeur',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
    ]
