# Generated by Django 2.1.1 on 2018-10-14 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membre', '0028_auto_20181014_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionTrader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_converti', models.PositiveIntegerField(null=True, verbose_name='Somme Convert')),
                ('epounds_transferer', models.PositiveIntegerField(null=True, verbose_name='Somme Convert')),
                ('solde_apres_conversion', models.PositiveIntegerField(null=True, verbose_name='Somme après Conversion')),
                ('date_conversion', models.DateTimeField(auto_now_add=True, verbose_name='Date de conversion')),
                ('consommateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.Consommateur', verbose_name='Consommateur')),
                ('trader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.Trader', verbose_name='Trader')),
            ],
            options={
                'verbose_name': 'Conversion',
                'verbose_name_plural': 'Conversions',
            },
        ),
        migrations.CreateModel(
            name='ReconversionTrader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epound_reconverti', models.PositiveIntegerField(verbose_name='Unités epouns Reconverties')),
                ('montant_retourner', models.PositiveIntegerField(null=True, verbose_name=' Montant Retour')),
                ('solde_consommateur_apres_reconversion', models.PositiveIntegerField(null=True, verbose_name='Solde après Reconversion')),
                ('date_conversion', models.DateTimeField(auto_now_add=True, verbose_name='Date de conversion')),
                ('consommateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.Consommateur', verbose_name='Consommateur')),
                ('trader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.Trader', verbose_name='Trader')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCommercialComsommateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_envoyer', models.PositiveIntegerField(null=True, verbose_name='Montant')),
                ('solde_apres_transaction', models.PositiveIntegerField(null=True, verbose_name='Solde après transaction')),
                ('date_transaction', models.DateTimeField(auto_now_add=True, verbose_name='Date de Transaction')),
                ('envoyeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envoyeur_commercial', to='membre.EntrepriseCommerciale', verbose_name='Envoyeur')),
                ('receveur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.Consommateur', verbose_name='receveur_consommateur')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionInterComsommateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_envoyer', models.PositiveIntegerField(verbose_name='Montant')),
                ('solde_apres_transaction', models.PositiveIntegerField(null=True, verbose_name='Solde après transaction')),
                ('date_transaction', models.DateTimeField(auto_now_add=True, verbose_name='Date de Transaction')),
                ('envoyeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envoyeur_consommateur', to='membre.Consommateur', verbose_name='Envoyeur')),
                ('receveur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.Consommateur', verbose_name='receveur')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
