# Generated by Django 2.1.1 on 2018-10-14 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionintercomsommateur',
            name='envoyeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envoyeur_consommateur', to='membre.ConsommateurParticulier', verbose_name='Envoyeur'),
        ),
        migrations.AlterField(
            model_name='transactionintercomsommateur',
            name='receveur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.ConsommateurParticulier', verbose_name='receveur'),
        ),
    ]
