# Generated by Django 2.1.1 on 2018-10-14 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20181014_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionintercomsommateur',
            name='envoyeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envoyeur_consommateur', to='membre.Consommateur', verbose_name='Envoyeur'),
        ),
        migrations.AlterField(
            model_name='transactionintercomsommateur',
            name='receveur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.Consommateur', verbose_name='receveur'),
        ),
    ]
