# Generated by Django 2.1.1 on 2018-01-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20181014_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=150, null=True)),
                ('message', models.TextField(null=True)),
                ('etat', models.PositiveIntegerField(null=True)),
                ('date_notif', models.DateTimeField(auto_now_add=True, null=True)),
                ('type_notif', models.PositiveIntegerField(null=True)),
                ('sender', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='transactioncommercialcomsommateur',
            name='envoyeur_code',
            field=models.PositiveIntegerField(null=True, verbose_name="Code membre de l'envoyeur"),
        ),
        migrations.AddField(
            model_name='transactioncommercialcomsommateur',
            name='receveur_code',
            field=models.PositiveIntegerField(null=True, verbose_name='Code membre du bénéficiare'),
        ),
    ]
