# Generated by Django 2.1.1 on 2018-10-18 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0033_auto_20181018_0230'),
        ('archive', '0007_auto_20181018_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayementInterCommercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envoyeur_code', models.PositiveIntegerField(null=True, verbose_name="Code membre de l'envoyeur")),
                ('receveur_code', models.PositiveIntegerField(null=True, verbose_name='Code membre du bénéficiare')),
                ('montant_envoyer', models.PositiveIntegerField(null=True, verbose_name='Montant transférer')),
                ('solde_apres_transaction', models.PositiveIntegerField(null=True, verbose_name='Solde après transaction')),
                ('date_transaction', models.DateTimeField(auto_now_add=True, verbose_name='Date de Transaction')),
                ('envoyeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_envoyeur', to='membre.EntrepriseCommerciale', verbose_name='Entreprise Acheteur')),
                ('receveur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_beneficiaire', to='membre.EntrepriseCommerciale', verbose_name='Entreprise bénéficiaire')),
            ],
        ),
    ]
