# Generated by Django 2.1.1 on 2018-10-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0035_auto_20181018_1511'),
        ('archive', '0009_creationparticulierpartrader'),
    ]

    operations = [
        migrations.AddField(
            model_name='creationparticulierpartrader',
            name='code_trader',
            field=models.PositiveIntegerField(null=True, verbose_name='Code du Trader'),
        ),
        migrations.AddField(
            model_name='creationparticulierpartrader',
            name='consommateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.ConsommateurParticulier'),
        ),
        migrations.AddField(
            model_name='creationparticulierpartrader',
            name='mdp',
            field=models.CharField(max_length=50, null=True, verbose_name='Mot de passe'),
        ),
        migrations.AddField(
            model_name='creationparticulierpartrader',
            name='telephone',
            field=models.CharField(max_length=8, null=True, verbose_name='Téléphone du client'),
        ),
        migrations.AddField(
            model_name='creationparticulierpartrader',
            name='trader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.Trader'),
        ),
    ]
