# Generated by Django 2.1.1 on 2018-10-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_creationentreprisepartrader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creationparticulierpartrader',
            name='consommateur',
        ),
        migrations.RemoveField(
            model_name='creationparticulierpartrader',
            name='trader',
        ),
        migrations.DeleteModel(
            name='CreationParticulierParTrader',
        ),
    ]
