# Generated by Django 2.1.1 on 2018-10-27 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_auto_20181025_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactioncommercialcomsommateur',
            options={'verbose_name': 'Transaction Commercial Consommateur', 'verbose_name_plural': 'Transactions Commercials Consommateurs'},
        ),
        migrations.AlterModelOptions(
            name='transactionintercomsommateur',
            options={'verbose_name': 'Transaction entre Consommateurs', 'verbose_name_plural': 'Transactions entre Consommateurs'},
        ),
    ]
