# Generated by Django 2.1.2 on 2018-10-31 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_auto_20181027_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payementconsomateur',
            options={'verbose_name': 'Transaction acheteur vers vendeur', 'verbose_name_plural': 'Transactions acheteurs vers vendeurs'},
        ),
        migrations.AlterModelOptions(
            name='payementintercommercial',
            options={'verbose_name': 'Transaction vendeur vers vendeur', 'verbose_name_plural': 'Transactions vendeurs vers vendeurs'},
        ),
    ]
