# Generated by Django 2.1.2 on 2018-11-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_auto_20181031_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactioncommercialcomsommateur',
            options={'verbose_name': 'Transfert Commercial Consommateur', 'verbose_name_plural': 'Transferts Commercials Consommateurs'},
        ),
        migrations.AlterModelOptions(
            name='transactionintercomsommateur',
            options={'verbose_name': 'Transfert entre Consommateurs', 'verbose_name_plural': 'Transferts entre Consommateurs'},
        ),
        migrations.RemoveField(
            model_name='transactionintercomsommateur',
            name='envoyeur_code',
        ),
        migrations.RemoveField(
            model_name='transactionintercomsommateur',
            name='receveur_code',
        ),
        migrations.RemoveField(
            model_name='transactionintercomsommateur',
            name='solde_apres_transaction',
        ),
        migrations.AddField(
            model_name='transactionintercomsommateur',
            name='numero_envoyeur',
            field=models.CharField(max_length=8, null=True, verbose_name="Numéro de l'envoyeur"),
        ),
        migrations.AddField(
            model_name='transactionintercomsommateur',
            name='numero_receveur',
            field=models.CharField(max_length=8, null=True, verbose_name='Numéro du bénéficiare'),
        ),
    ]
