# Generated by Django 2.1.2 on 2018-11-18 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0061_auto_20181118_0930'),
        ('ecommerce', '0022_auto_20181118_0930'),
        ('archive', '0015_auto_20181118_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_client', models.CharField(max_length=8, null=True, verbose_name='Numéro du client')),
                ('numero_vendeur', models.CharField(max_length=8, null=True, verbose_name='Numéro du vendeur')),
                ('code_produit', models.CharField(blank=True, max_length=100, unique=True, verbose_name="Code de l'article")),
                ('quantite', models.PositiveIntegerField(null=True, verbose_name='Quantité')),
                ('a_livrer', models.BooleanField(verbose_name='Article à liver')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.Consommateur')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Produit')),
                ('vendeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.EntrepriseCommerciale')),
            ],
        ),
    ]
