# Generated by Django 2.1.2 on 2018-11-19 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0062_auto_20181119_1649'),
        ('archive', '0016_commandeclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendeurVente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acheteur', models.CharField(max_length=8, null=True, verbose_name="Numéro de l'acheteur")),
                ('numero_vendeur', models.CharField(max_length=8, null=True, verbose_name='Numéro du vendeur')),
                ('montant', models.PositiveIntegerField(null=True, verbose_name='Montant')),
                ('acheteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.Consommateur')),
                ('vendeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.EntrepriseCommerciale')),
            ],
        ),
    ]
