# Generated by Django 2.1.2 on 2018-11-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0017_vendeurvente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversiontrader',
            name='receveur_code',
        ),
        migrations.RemoveField(
            model_name='conversiontrader',
            name='trader_code',
        ),
        migrations.RemoveField(
            model_name='reconversiontrader',
            name='receveur_code',
        ),
        migrations.RemoveField(
            model_name='reconversiontrader',
            name='trader_code',
        ),
        migrations.AddField(
            model_name='conversiontrader',
            name='numero_receveur',
            field=models.CharField(max_length=8, null=True, verbose_name='Numéro du Consommateur'),
        ),
        migrations.AddField(
            model_name='conversiontrader',
            name='numero_trader',
            field=models.CharField(max_length=8, null=True, verbose_name='Numéro du trader'),
        ),
        migrations.AddField(
            model_name='reconversiontrader',
            name='numero_receveur',
            field=models.CharField(max_length=8, null=True, verbose_name='Numéro du Consommateur'),
        ),
        migrations.AddField(
            model_name='reconversiontrader',
            name='numero_trader',
            field=models.CharField(max_length=8, null=True, verbose_name='Numéro du trader'),
        ),
    ]
