# Generated by Django 2.1.2 on 2018-11-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0018_auto_20181119_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeclient',
            name='code_produit',
            field=models.CharField(blank=True, max_length=100, verbose_name="Code de l'article"),
        ),
    ]
