# Generated by Django 2.1.2 on 2018-11-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0019_auto_20181120_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeclient',
            name='etat',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='valider',
            field=models.BooleanField(default=False, verbose_name='Valider'),
        ),
    ]
