# Generated by Django 2.1.2 on 2018-12-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0020_auto_20181120_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='payementconsomateur',
            name='telephone_envoyeur',
            field=models.CharField(max_length=8, null=True, verbose_name="Téléphone de l'envoyeur"),
        ),
        migrations.AddField(
            model_name='payementconsomateur',
            name='telephone_receveur',
            field=models.CharField(max_length=8, null=True, verbose_name='Téléphone du receveur'),
        ),
    ]
