# Generated by Django 2.1.2 on 2018-12-11 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0021_auto_20181203_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeclient',
            name='date_commande',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
