# Generated by Django 2.1.2 on 2018-12-13 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0065_auto_20181213_2111'),
        ('archive', '0022_commandeclient_date_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactivationClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_trader', models.CharField(max_length=8, null=True, verbose_name='Numéro du trader')),
                ('numero_receveur', models.CharField(max_length=8, null=True, verbose_name='Numéro du Consommateur')),
                ('date_reabonnement', models.DateTimeField(auto_now_add=True, verbose_name='Date de réabonnement')),
                ('consommateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.Consommateur', verbose_name='Consommateur')),
                ('trader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.Trader', verbose_name='Trader')),
            ],
        ),
    ]
