# Generated by Django 2.1.2 on 2018-12-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0023_reactivationclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioncommercialcomsommateur',
            name='envoyeur_code',
        ),
        migrations.RemoveField(
            model_name='transactioncommercialcomsommateur',
            name='receveur_code',
        ),
        migrations.AddField(
            model_name='transactioncommercialcomsommateur',
            name='numero_envoyeur',
            field=models.CharField(max_length=8, null=True, verbose_name="Numéro de l'envoyeur"),
        ),
        migrations.AddField(
            model_name='transactioncommercialcomsommateur',
            name='numero_receveur',
            field=models.CharField(max_length=8, null=True, verbose_name='Numéro du bénéficiare'),
        ),
    ]
