# Generated by Django 2.1.2 on 2018-12-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0025_auto_20181215_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True, verbose_name='Contenu du méssage')),
            ],
        ),
    ]
