# Generated by Django 2.1.2 on 2018-12-27 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0026_messageclient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversiontrader',
            options={'verbose_name': 'Conversion Trader', 'verbose_name_plural': 'Conversions Traders'},
        ),
        migrations.AlterModelOptions(
            name='payementconsomateur',
            options={'verbose_name': 'Transaction consommateur vers vendeur', 'verbose_name_plural': 'Transactions consommateurs vers vendeurs'},
        ),
        migrations.AlterModelOptions(
            name='transactioncommercialcomsommateur',
            options={'verbose_name': 'Transfert Commercial vers Consommateur', 'verbose_name_plural': 'Transferts Commercials vers Consommateurs'},
        ),
        migrations.AlterModelOptions(
            name='transactionintercomsommateur',
            options={'verbose_name': 'Transfert Consommateurs vers Consommateurs', 'verbose_name_plural': 'Transfert Consommateurs vers Consommateurs'},
        ),
        migrations.AddField(
            model_name='messageclient',
            name='date_envoye',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='messageclient',
            name='telephone',
            field=models.CharField(max_length=8, null=True, verbose_name='Téléphone du client'),
        ),
        migrations.AlterField(
            model_name='payementconsomateur',
            name='envoyeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.Consommateur', verbose_name='Expéditeur'),
        ),
        migrations.AlterField(
            model_name='payementintercommercial',
            name='envoyeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_envoyeur', to='membre.EntrepriseCommerciale', verbose_name='Entreprise Expéditeur'),
        ),
        migrations.AlterField(
            model_name='reconversiontrader',
            name='montant_retourner',
            field=models.PositiveIntegerField(null=True, verbose_name=' Montant Retourner'),
        ),
        migrations.AlterField(
            model_name='transactioncommercialcomsommateur',
            name='envoyeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envoyeur_commercial', to='membre.EntrepriseCommerciale', verbose_name='Expéditeur'),
        ),
        migrations.AlterField(
            model_name='transactioncommercialcomsommateur',
            name='receveur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.Consommateur', verbose_name='Entreprise bénéficiaire'),
        ),
        migrations.AlterField(
            model_name='transactionintercomsommateur',
            name='envoyeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envoyeur_consommateur', to='membre.Consommateur', verbose_name='Expéditeur'),
        ),
    ]
