# Generated by Django 2.1.2 on 2019-01-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0027_auto_20181227_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeurvente',
            name='mdp_acheteur',
            field=models.CharField(max_length=50, null=True, verbose_name='Mot de passe client'),
        ),
    ]
