# Generated by Django 2.1.2 on 2019-01-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0028_vendeurvente_mdp_acheteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconversiontrader',
            name='mdp',
            field=models.CharField(max_length=80, null=True, verbose_name='Mot de passe du Consommateur'),
        ),
    ]
