# Generated by Django 2.1.2 on 2019-03-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0030_auto_20190131_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendeurvente',
            options={'verbose_name': 'Vente effectué', 'verbose_name_plural': 'Ventes effectuées'},
        ),
    ]
