# Generated by Django 2.1.2 on 2019-05-13 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0092_membre_code_qr'),
        ('archive', '0031_auto_20190319_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayementInterCommercialAvecCompteConsommation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_envoyeur', models.CharField(max_length=8, null=True, verbose_name="Numéro de l'envoyeur")),
                ('numero_receveur', models.CharField(max_length=8, null=True, verbose_name='Numéro du bénéficiare')),
                ('montant_envoyer', models.PositiveIntegerField(null=True, verbose_name='Montant transférer')),
                ('solde_apres_transaction', models.PositiveIntegerField(null=True, verbose_name='Solde après transaction')),
                ('date_transaction', models.DateTimeField(auto_now_add=True, verbose_name='Date de Transaction')),
                ('envoyeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_envoyeur_sur_compte_conso', to='membre.EntrepriseCommerciale', verbose_name='Entreprise Expéditeur')),
                ('receveur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_beneficiaire_sur_compte_vente', to='membre.EntrepriseCommerciale', verbose_name='Entreprise bénéficiaire')),
            ],
            options={
                'verbose_name': 'Transaction vendeur vers vendeur',
                'verbose_name_plural': 'Transactions vendeurs vers vendeurs',
            },
        ),
    ]
