# Generated by Django 2.1.2 on 2020-01-12 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0032_auto_20190513_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransfertCompteVendeurSurCompteConsommateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vendeur', models.CharField(max_length=8, null=True, verbose_name="Numéro de l'envoyeur")),
                ('montant_transferer', models.PositiveIntegerField(null=True, verbose_name='Montant transférer')),
                ('date_transfert', models.DateTimeField(auto_now_add=True, verbose_name='Date de transfert')),
                ('vendeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.EntrepriseCommerciale', verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Transfert Commercial vers Consommateur',
                'verbose_name_plural': 'Transferts Commercials vers Consommateurs',
            },
        ),
    ]
