# Generated by Django 2.1.2 on 2020-01-12 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0033_auto_20200112_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfertcomptevendeursurcompteconsommateur',
            options={'verbose_name': 'Transfert Compte Vendeur vers Compte Consommateur du Vendeur', 'verbose_name_plural': 'Transferts Comptes Vendeur vers Comptes Consommateur des Vendeurs'},
        ),
        migrations.AddField(
            model_name='conversiontrader',
            name='vendeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.EntrepriseCommerciale', verbose_name='Consommateur'),
        ),
    ]
