# Generated by Django 2.1.1 on 2018-09-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionUnites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_debouse', models.PositiveIntegerField(verbose_name='Montant déboursé')),
                ('unite_epound_correspondant', models.PositiveIntegerField(verbose_name='e-pounds correspondant')),
                ('mdp', models.CharField(max_length=100, verbose_name='Confirmez votre mot de passe')),
            ],
            options={
                'verbose_name': "Emission d'unité",
                'verbose_name_plural': "Emission d'unités",
            },
        ),
    ]
