# Generated by Django 2.1.1 on 2018-09-26 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emision', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionunites',
            name='beneficiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='membre.Membre', verbose_name='Bénéficiaire'),
        ),
        migrations.AddField(
            model_name='emissionunites',
            name='operateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Opérateur'),
        ),
    ]
