# Generated by Django 2.1.1 on 2018-10-25 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emision', '0003_auto_20181006_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionSurCompteGrenier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant Emit')),
                ('password', models.CharField(max_length=100, verbose_name='Confirmez votre mot de passe')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
