# Generated by Django 2.1.1 on 2018-10-25 13:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emision', '0004_emissionsurcomptegrenier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmissionSurCompteGrenier',
            new_name='EmissionSurCompteAlpha',
        ),
    ]
