# Generated by Django 2.1.1 on 2018-10-25 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membre', '0045_auto_20181025_1431'),
        ('emision', '0005_auto_20181025_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionSurCompteTrader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant Emit')),
                ('bonification', models.PositiveIntegerField(editable=False, verbose_name='Bonnification')),
                ('password', models.CharField(max_length=100, verbose_name='Confirmez votre mot de passe')),
                ('trader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.Trader', verbose_name='Bénéficiaire')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
