# Generated by Django 2.1.1 on 2018-10-25 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emision', '0006_emissionsurcomptetrader'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionsurcomptealpha',
            name='date_emission',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emissionsurcomptetrader',
            name='date_emission',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
