# Generated by Django 2.1.1 on 2018-10-25 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emision', '0009_creationparticulierpartrader'),
    ]

    operations = [
        migrations.AddField(
            model_name='creationparticulierpartrader',
            name='date_emission',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creationparticulierpartrader',
            name='solde_initial',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='Solde initial du Trader'),
        ),
    ]
