# Generated by Django 2.1.1 on 2018-10-27 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0051_auto_20181027_2002'),
        ('emision', '0012_emissionsurcompteconsommateur_operateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionsurcompteconsommateur',
            name='operateur',
        ),
        migrations.AddField(
            model_name='emissionsurcompteconsommateur',
            name='trader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.Trader', verbose_name='Trader'),
        ),
    ]
