# Generated by Django 2.1.2 on 2018-12-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emision', '0014_auto_20181119_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creationparticulierpartrader',
            name='mdp',
        ),
    ]
