# Generated by Django 2.1.2 on 2019-01-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emision', '0015_remove_creationparticulierpartrader_mdp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creationparticulierpartrader',
            options={'verbose_name': 'Adhésion', 'verbose_name_plural': 'Adhésions'},
        ),
    ]
