# Generated by Django 2.1.2 on 2019-04-06 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emision', '0016_auto_20190119_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creationparticulierpartrader',
            name='consommateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.ConsommateurParticulier'),
        ),
    ]
