# Generated by Django 2.1.2 on 2019-08-17 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0094_membre_code_qr'),
        ('emision', '0017_auto_20190406_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreationParticulierParTraderEtIntegrateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_trader', models.CharField(max_length=8, null=True, verbose_name='Numero du Trader')),
                ('numero_integrateur', models.CharField(max_length=8, null=True, verbose_name='Numero du Trader')),
                ('telephone', models.CharField(max_length=8, null=True, verbose_name='Téléphone du client')),
                ('solde_initial', models.PositiveIntegerField(editable=False, null=True, verbose_name='Solde initial du Trader')),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('consommateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new', to='membre.ConsommateurParticulier')),
                ('integrateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ancient', to='membre.ConsommateurParticulier')),
                ('trader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membre.Trader')),
            ],
            options={
                'verbose_name': 'Adhésion par membre',
                'verbose_name_plural': 'Adhésions par membres',
            },
        ),
    ]
