# Generated by Django 2.1.2 on 2018-11-02 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemeSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probleme', models.CharField(max_length=250, null=True, verbose_name='Question')),
                ('solution', models.TextField(null=True, verbose_name='Réponse')),
            ],
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=250, null=True, verbose_name='Téléphone du client')),
            ],
        ),
        migrations.AddField(
            model_name='problemesolution',
            name='sujet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faqs.Sujet'),
        ),
    ]
