# Generated by Django 2.1.2 on 2018-11-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujet',
            name='slug',
            field=models.SlugField(max_length=80, null=True, verbose_name='Etiquette'),
        ),
        migrations.AlterField(
            model_name='sujet',
            name='sujet',
            field=models.CharField(max_length=250, null=True, verbose_name='Sujet'),
        ),
    ]
