# Generated by Django 2.1.2 on 2018-11-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_auto_20181114_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemesolution',
            name='manuel',
            field=models.FileField(blank=True, null=True, upload_to='manuels_utilisations/%Y/%m/%d/'),
        ),
    ]
