# Generated by Django 2.1.2 on 2019-09-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0003_problemesolution_manuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(null=True, verbose_name='Réponse')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
