# Generated by Django 2.1.2 on 2019-10-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0004_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(null=True, verbose_name='Questions Utilisateurs'),
        ),
    ]
