# Generated by Django 2.1.1 on 2018-09-26 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compte', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('code_membre', models.CharField(max_length=50, verbose_name='Code membre')),
                ('mdp', models.CharField(max_length=80, verbose_name='Mot de passe')),
                ('date_expiration', models.DateTimeField(verbose_name="Date d'expiration")),
                ('actif', models.BooleanField(default=True, verbose_name='En activité')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='EntrepriseCommerciale',
            fields=[
                ('membre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='membre.Membre')),
                ('compte_entreprise_commercial', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='compte.CompteEntrepriseCommerciale', verbose_name='Compte e-B')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('membre.membre',),
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('membre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='membre.Membre')),
                ('type_personne', models.CharField(choices=[('Personne physique', 'Personne morale'), ('Personne morale', 'Personne physique')], default='Personne physique', max_length=50)),
                ('prenoms', models.CharField(max_length=150, null=True, verbose_name='Prénoms')),
                ('compte_trader', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='compte.CompteTrader', verbose_name='Compte e-T')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('membre.membre',),
        ),
        migrations.AddField(
            model_name='membre',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_membre.membre_set+', to='contenttypes.ContentType'),
        ),
    ]
