# Generated by Django 2.1.1 on 2018-09-28 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_auto_20180928_1112'),
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consommateur',
            fields=[
                ('membre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='membre.Membre')),
                ('nationalite', models.CharField(choices=[('TOGO', 'TOGO'), ('BENIN', 'BENIN'), ('GHANA', 'GHANA')], default='TOGO', max_length=50, null=True)),
                ('compte_consommateur', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='compte.CompteConsommateur', verbose_name='Compte e-C')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('membre.membre',),
        ),
    ]
