# Generated by Django 2.1.1 on 2018-09-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0002_consommateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsommateurEntreprise',
            fields=[
                ('consommateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='membre.Consommateur')),
                ('raison_social', models.CharField(max_length=100, verbose_name='Raison sociale')),
                ('statut_juridique', models.CharField(max_length=100, verbose_name='Statut juridique')),
                ('objet_social', models.CharField(max_length=100, verbose_name='Objet sociale')),
                ('capital_social', models.PositiveIntegerField(verbose_name='Caplital sociale')),
                ('numero_rccm', models.CharField(max_length=100, verbose_name='Numéro RCCM')),
                ('regime_fiscal', models.CharField(max_length=100, verbose_name='Régime fiscal')),
                ('nif', models.CharField(max_length=100, verbose_name='NIF')),
                ('siege_social', models.CharField(max_length=100, verbose_name='Siège sociale')),
                ('numero_compte_bancaire', models.CharField(max_length=100, verbose_name='Numéro de compte bancaire')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('membre.consommateur',),
        ),
        migrations.CreateModel(
            name='ConsommateurParticulier',
            fields=[
                ('consommateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='membre.Consommateur')),
                ('prenoms', models.CharField(max_length=150, null=True, verbose_name='Prénoms')),
                ('date_naissance', models.DateField(null=True, verbose_name='Date de naissance')),
                ('lieu_residence', models.CharField(max_length=150, null=True, verbose_name='Lieu de résidence')),
                ('contact', models.CharField(max_length=50, null=True, verbose_name='Contact')),
                ('num_carte', models.CharField(max_length=12, null=True, verbose_name="Numéro de carte d'indentité")),
                ('formation', models.CharField(max_length=100, null=True, verbose_name='Formation')),
                ('profession', models.CharField(max_length=100, null=True, verbose_name='Profession')),
                ('situation_matrimoniale', models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié', 'Marié')], default='Célibataire', max_length=50, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('membre.consommateur',),
        ),
    ]
