# Generated by Django 2.1.1 on 2018-09-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0003_consommateurentreprise_consommateurparticulier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consommateurentreprise',
            options={'verbose_name': 'Entreprise', 'verbose_name_plural': 'Entreprises'},
        ),
        migrations.AlterModelOptions(
            name='consommateurparticulier',
            options={'verbose_name': 'Particulier', 'verbose_name_plural': 'Particuliers'},
        ),
        migrations.AlterModelOptions(
            name='entreprisecommerciale',
            options={'verbose_name': 'Vendeur', 'verbose_name_plural': 'Vendeurs'},
        ),
        migrations.AlterField(
            model_name='membre',
            name='code_membre',
            field=models.PositiveIntegerField(unique=True, verbose_name='Code membre'),
        ),
    ]
