# Generated by Django 2.1.1 on 2018-09-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0004_auto_20180930_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommateur',
            name='nationalite',
            field=models.CharField(choices=[('TOGO', 'TOGO'), ('BENIN', 'BENIN'), ('GHANA', 'GHANA')], default='TOGO', max_length=50, null=True, verbose_name='Pays'),
        ),
    ]
