# Generated by Django 2.1.1 on 2018-10-01 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0006_auto_20181001_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 0, 46, 28, 649076), verbose_name="Date d'expiration"),
        ),
    ]
