# Generated by Django 2.1.1 on 2018-10-01 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0007_auto_20181001_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 1, 37, 13, 795767), verbose_name="Date d'expiration"),
        ),
    ]
