# Generated by Django 2.1.1 on 2018-09-30 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0008_auto_20181001_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 23, 15, 47, 59644), verbose_name="Date d'expiration"),
        ),
    ]
