# Generated by Django 2.1.1 on 2018-10-06 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0014_auto_20181006_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='code_membre',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Code membre'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 14, 41, 52, 537067), verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='membre',
            name='mdp',
            field=models.CharField(max_length=80, null=True, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='nom',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
    ]
