# Generated by Django 2.1.1 on 2018-10-06 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0015_auto_20181006_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 15, 4, 30, 755167), verbose_name="Date d'expiration"),
        ),
    ]
