# Generated by Django 2.1.1 on 2018-10-06 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0018_auto_20181006_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='type_personne',
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 15, 35, 3, 27432), verbose_name="Date d'expiration"),
        ),
    ]
