# Generated by Django 2.1.1 on 2018-10-14 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0023_auto_20181006_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 7, 52, 12, 672802), verbose_name="Date d'expiration"),
        ),
    ]
