# Generated by Django 2.1.1 on 2018-10-14 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0027_auto_20181014_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 13, 27, 54, 360890), verbose_name="Date d'expiration"),
        ),
    ]
