# Generated by Django 2.1.1 on 2018-10-17 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0029_auto_20181017_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 16, 20, 45, 374634), verbose_name="Date d'expiration"),
        ),
    ]
