# Generated by Django 2.1.1 on 2018-10-17 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0030_auto_20181017_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 18, 24, 42, 909358), verbose_name="Date d'expiration"),
        ),
    ]
