# Generated by Django 2.1.1 on 2018-10-18 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0031_auto_20181017_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 2, 16, 45, 259581), verbose_name="Date d'expiration"),
        ),
    ]
