# Generated by Django 2.1.1 on 2018-10-18 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0032_auto_20181018_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 2, 30, 37, 716346), verbose_name="Date d'expiration"),
        ),
    ]
