# Generated by Django 2.1.1 on 2018-10-18 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0037_auto_20181018_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 14, 59, 28, 190419), verbose_name="Date d'expiration"),
        ),
    ]
