# Generated by Django 2.1.1 on 2018-10-18 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0038_auto_20181018_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommateurentreprise',
            name='capital_social',
            field=models.PositiveIntegerField(null=True, verbose_name='Caplital sociale'),
        ),
        migrations.AlterField(
            model_name='consommateurentreprise',
            name='nif',
            field=models.CharField(max_length=100, null=True, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='consommateurentreprise',
            name='numero_compte_bancaire',
            field=models.CharField(max_length=100, null=True, verbose_name='Numéro de compte bancaire'),
        ),
        migrations.AlterField(
            model_name='consommateurentreprise',
            name='numero_rccm',
            field=models.CharField(max_length=100, null=True, verbose_name='Numéro RCCM'),
        ),
        migrations.AlterField(
            model_name='consommateurentreprise',
            name='objet_social',
            field=models.CharField(max_length=100, null=True, verbose_name='Objet sociale'),
        ),
        migrations.AlterField(
            model_name='consommateurentreprise',
            name='raison_social',
            field=models.CharField(max_length=100, null=True, verbose_name='Raison sociale'),
        ),
        migrations.AlterField(
            model_name='consommateurentreprise',
            name='regime_fiscal',
            field=models.CharField(max_length=100, null=True, verbose_name='Régime fiscal'),
        ),
        migrations.AlterField(
            model_name='consommateurentreprise',
            name='responsable',
            field=models.CharField(max_length=100, null=True, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='consommateurentreprise',
            name='siege_social',
            field=models.CharField(max_length=100, null=True, verbose_name='Siège sociale'),
        ),
        migrations.AlterField(
            model_name='consommateurentreprise',
            name='statut_juridique',
            field=models.CharField(max_length=100, null=True, verbose_name='Statut juridique'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 15, 9, 4, 772996), verbose_name="Date d'expiration"),
        ),
    ]
