# Generated by Django 2.1.1 on 2018-10-19 20:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_expressionbesoin'),
        ('membre', '0039_auto_20181018_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprisecommerciale',
            name='besoin_gere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.ExpressionBesoin', verbose_name="Domaine d'activité"),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 20, 4, 17, 627395), verbose_name="Date d'expiration"),
        ),
    ]
