# Generated by Django 2.1.1 on 2018-10-23 14:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_spécificationbesoin'),
        ('membre', '0042_auto_20181023_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprisecommerciale',
            name='besoin_gere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.SpécificationBesoin', verbose_name="Domaine d'activité"),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 12, 14, 27, 19, 78412), verbose_name="Date d'expiration"),
        ),
    ]
