# Generated by Django 2.1.1 on 2018-10-24 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0043_auto_20181023_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 18, 58, 20, 325616), verbose_name="Date d'expiration"),
        ),
    ]
