# Generated by Django 2.1.1 on 2018-10-25 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0046_auto_20181025_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 16, 31, 32, 645194), verbose_name="Date d'expiration"),
        ),
    ]
