# Generated by Django 2.1.1 on 2018-10-27 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0048_auto_20181027_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 16, 53, 11, 697634), verbose_name="Date d'expiration"),
        ),
    ]
