# Generated by Django 2.1.1 on 2018-10-27 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0049_auto_20181027_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 19, 54, 12, 278707), verbose_name="Date d'expiration"),
        ),
    ]
