# Generated by Django 2.1.1 on 2018-10-27 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0050_auto_20181027_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 20, 2, 57, 739796), verbose_name="Date d'expiration"),
        ),
    ]
