# Generated by Django 2.1.2 on 2018-10-31 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0051_auto_20181027_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 11, 6, 21, 40529), verbose_name="Date d'expiration"),
        ),
    ]
