# Generated by Django 2.1.2 on 2018-11-01 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0052_auto_20181031_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 0, 45, 21, 584007), verbose_name="Date d'expiration"),
        ),
    ]
