# Generated by Django 2.1.2 on 2018-11-01 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0053_auto_20181101_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 1, 48, 57, 826349), verbose_name="Date d'expiration"),
        ),
    ]
