# Generated by Django 2.1.2 on 2018-11-09 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0057_auto_20181109_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 29, 18, 28, 45, 590550), verbose_name="Date d'expiration"),
        ),
    ]
