# Generated by Django 2.1.2 on 2018-11-09 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0058_auto_20181109_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprisecommerciale',
            name='banniere_cinq',
            field=models.ImageField(blank=True, null=True, upload_to='banniere cinq/'),
        ),
        migrations.AlterField(
            model_name='entreprisecommerciale',
            name='banniere_principal',
            field=models.ImageField(blank=True, null=True, upload_to='banniere principal/'),
        ),
        migrations.AlterField(
            model_name='entreprisecommerciale',
            name='banniere_quatre',
            field=models.ImageField(blank=True, null=True, upload_to='banniere quatre/'),
        ),
        migrations.AlterField(
            model_name='entreprisecommerciale',
            name='banniere_secondaire',
            field=models.ImageField(blank=True, null=True, upload_to='banniere secondaire/'),
        ),
        migrations.AlterField(
            model_name='entreprisecommerciale',
            name='banniere_trois',
            field=models.ImageField(blank=True, null=True, upload_to='banniere trois/'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 29, 18, 53, 15, 19434), verbose_name="Date d'expiration"),
        ),
    ]
