# Generated by Django 2.1.2 on 2018-11-14 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0059_auto_20181109_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprisecommerciale',
            name='emplacement',
            field=models.CharField(max_length=200, null=True, verbose_name='Emplacement du Vendeur'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 4, 58, 7, 676408), verbose_name="Date d'expiration"),
        ),
    ]
