# Generated by Django 2.1.2 on 2018-11-18 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0060_auto_20181114_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 9, 30, 23, 106589), verbose_name="Date d'expiration"),
        ),
    ]
