# Generated by Django 2.1.2 on 2018-11-19 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0061_auto_20181118_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 16, 49, 27, 771175), verbose_name="Date d'expiration"),
        ),
    ]
