# Generated by Django 2.1.2 on 2018-11-26 13:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_auto_20181118_0930'),
        ('membre', '0062_auto_20181119_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprisecommerciale',
            name='besoin_fondamental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.ExpressionBesoin', verbose_name="Domaine d'activité"),
        ),
        migrations.AlterField(
            model_name='entreprisecommerciale',
            name='besoin_gere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.SpécificationBesoin', verbose_name="Domaine d'activité"),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 13, 24, 2, 354432), verbose_name="Date d'expiration"),
        ),
    ]
