# Generated by Django 2.1.2 on 2018-12-01 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0063_auto_20181126_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprisecommerciale',
            name='type_market',
            field=models.CharField(choices=[('es', 'es'), ('em', 'em')], default='es', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 15, 18, 42, 187891), verbose_name="Date d'expiration"),
        ),
    ]
