# Generated by Django 2.1.2 on 2018-12-13 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0064_auto_20181201_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 21, 11, 28, 516270), verbose_name="Date d'expiration"),
        ),
    ]
