# Generated by Django 2.1.2 on 2018-12-27 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0067_auto_20181213_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='emplacement',
            field=models.CharField(max_length=200, null=True, verbose_name='Emplacement du Trader'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 19, 50, 36, 27969), verbose_name="Date d'expiration"),
        ),
    ]
