# Generated by Django 2.1.2 on 2019-01-11 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0068_auto_20181227_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprisecommerciale',
            name='nature_jurique',
            field=models.CharField(choices=[('Etablissement', 'Etablissement'), ('SARL', 'SARL'), ('Société anonyme', 'Société anonyme')], default='Etablissement', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='entreprisecommerciale',
            name='nif',
            field=models.CharField(max_length=100, null=True, verbose_name='NIF'),
        ),
        migrations.AddField(
            model_name='entreprisecommerciale',
            name='numero_cnss',
            field=models.CharField(max_length=100, null=True, verbose_name='Numéro de CNSS'),
        ),
        migrations.AddField(
            model_name='entreprisecommerciale',
            name='numero_rccm',
            field=models.CharField(max_length=100, null=True, verbose_name='Numéro RCCM'),
        ),
        migrations.AddField(
            model_name='entreprisecommerciale',
            name='regime_fiscal',
            field=models.CharField(max_length=100, null=True, verbose_name='Régime fiscal'),
        ),
        migrations.AddField(
            model_name='entreprisecommerciale',
            name='responsable',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom et Prénoms du Responsable'),
        ),
        migrations.AddField(
            model_name='entreprisecommerciale',
            name='siege_social',
            field=models.CharField(max_length=100, null=True, verbose_name='Siège sociale'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 31, 10, 38, 27, 562719), verbose_name="Date d'expiration"),
        ),
    ]
