# Generated by Django 2.1.2 on 2019-01-11 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0070_auto_20190111_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True, verbose_name='Nom du partenaire')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo_partenaire/')),
            ],
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 31, 14, 51, 21, 182869), verbose_name="Date d'expiration"),
        ),
    ]
