# Generated by Django 2.1.2 on 2019-01-19 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0071_auto_20190111_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprisecommerciale',
            name='nature_jurique',
            field=models.CharField(blank=True, choices=[('Etablissement', 'Etablissement'), ('SNC', 'SNC'), ('SCS', 'SCS'), ('SA', 'SA'), ('SARL', 'SARL'), ('SEP', 'SEP'), ('SPAS', 'SPAS')], default='SNC', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='entreprisecommerciale',
            name='nif',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='entreprisecommerciale',
            name='numero_cnss',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de CNSS'),
        ),
        migrations.AlterField(
            model_name='entreprisecommerciale',
            name='numero_rccm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro RCCM'),
        ),
        migrations.AlterField(
            model_name='entreprisecommerciale',
            name='regime_fiscal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Régime fiscal'),
        ),
        migrations.AlterField(
            model_name='entreprisecommerciale',
            name='siege_social',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Siège sociale'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='code_membre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code membre'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 11, 49, 0, 553586), verbose_name="Date d'expiration"),
        ),
    ]
