# Generated by Django 2.1.2 on 2019-01-19 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0073_auto_20190119_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprisecommerciale',
            name='contact_1',
            field=models.CharField(max_length=8, null=True, verbose_name='Contact 1'),
        ),
        migrations.AddField(
            model_name='entreprisecommerciale',
            name='contact_2',
            field=models.CharField(max_length=8, null=True, verbose_name='Contact 2'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 13, 2, 39, 369614), verbose_name="Date d'expiration"),
        ),
    ]
