# Generated by Django 2.1.2 on 2019-01-19 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0074_auto_20190119_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprisecommerciale',
            name='contact_1',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Contact 1'),
        ),
        migrations.AlterField(
            model_name='entreprisecommerciale',
            name='contact_2',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Contact 2'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 13, 19, 11, 41623), verbose_name="Date d'expiration"),
        ),
    ]
