# Generated by Django 2.1.2 on 2019-01-21 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0075_auto_20190119_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprisecommerciale',
            name='objet_social',
            field=models.TextField(blank=True, null=True, verbose_name='Objet social'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 11, 34, 11, 868914), verbose_name="Date d'expiration"),
        ),
    ]
