# Generated by Django 2.1.2 on 2019-01-21 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0076_auto_20190121_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 14, 36, 24, 625440), verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='membre',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='telephone',
            field=models.CharField(max_length=8, null=True, unique=True, verbose_name='Téléphone'),
        ),
    ]
