# Generated by Django 2.1.2 on 2019-01-23 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0079_auto_20190123_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprisecommerciale',
            name='emplacement',
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 17, 43, 2, 181318), verbose_name="Date d'expiration"),
        ),
    ]
