# Generated by Django 2.1.2 on 2019-01-23 18:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0080_auto_20190123_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprisecommerciale',
            name='emplacement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quartier_entreprise', to='membre.Quartier'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 18, 21, 5, 631295), verbose_name="Date d'expiration"),
        ),
    ]
