# Generated by Django 2.1.2 on 2019-01-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0081_auto_20190123_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_expiration',
            field=models.DateTimeField(null=True, verbose_name="Date d'expiration"),
        ),
    ]
