# Generated by Django 2.1.2 on 2019-01-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0082_auto_20190123_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='emplacement',
        ),
    ]
