# Generated by Django 2.1.2 on 2019-02-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0085_auto_20190131_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='code_membre',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code membre'),
        ),
    ]
