# Generated by Django 2.1.2 on 2019-03-19 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0088_auto_20190223_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprisecommerciale',
            name='besoin_gere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.SpécificationBesoin', verbose_name="Sous domaine d'activité"),
        ),
    ]
