# Generated by Django 2.1.2 on 2019-04-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0089_auto_20190319_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprisecommerciale',
            name='nature_jurique',
            field=models.CharField(blank=True, choices=[('Etablissement', 'Etablissement'), ('SNC', 'SNC'), ('EI', 'EI'), ('ETS', 'ETS'), ('SCS', 'SCS'), ('SA', 'SA'), ('SARL', 'SARL'), ('SEP', 'SEP'), ('SPAS', 'SPAS')], default='SNC', max_length=150, null=True),
        ),
    ]
