# Generated by Django 2.1.2 on 2019-05-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0090_auto_20190406_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consommateur',
            options={'verbose_name': 'Particuliers et Entreprises', 'verbose_name_plural': 'Particuliers et Entreprises'},
        ),
        migrations.AlterModelOptions(
            name='consommateurentreprise',
            options={'verbose_name': 'Entreprise Consommatrice', 'verbose_name_plural': 'Entreprises Consommatrices'},
        ),
        migrations.AlterModelOptions(
            name='membre',
            options={'verbose_name': 'Tous les Utilisateurs', 'verbose_name_plural': 'Tous les Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='membre',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
