# Generated by Django 2.1.2 on 2019-06-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0091_auto_20190511_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consommateur',
            options={'verbose_name': 'Consommateur', 'verbose_name_plural': 'Consommateurs'},
        ),
    ]
