# Generated by Django 2.1.2 on 2019-07-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0092_auto_20190625_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommateur',
            name='nationalite',
            field=models.CharField(blank=True, choices=[('TOGO', 'TOGO'), ('BENIN', 'BENIN')], default='TOGO', max_length=50, null=True, verbose_name='Pays'),
        ),
    ]
