# Generated by Django 2.1.2 on 2019-08-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0093_auto_20190728_1241'),
    ]

    operations = [

    ]
