# Generated by Django 2.1.2 on 2019-10-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0094_membre_code_qr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quartier',
            options={'ordering': ['nom']},
        ),
        migrations.AddField(
            model_name='entreprisecommerciale',
            name='localisation',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
