# Generated by Django 2.1.2 on 2019-10-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0095_auto_20191016_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quartier',
            options={},
        ),
        migrations.AlterField(
            model_name='consommateur',
            name='nationalite',
            field=models.CharField(blank=True, choices=[('TOGO', 'TOGO'), ('BENIN', 'BENIN'), ('GHANA', 'GHANA')], default='TOGO', max_length=50, null=True, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='entreprisecommerciale',
            name='localisation',
            field=models.URLField(blank=True, null=True),
        ),
    ]
