# Generated by Django 2.1.2 on 2020-01-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0096_auto_20191017_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='code_qr',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Qr code'),
        ),
    ]
