# Generated by Django 2.1.2 on 2020-08-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0097_membre_code_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
