# Generated by Django 2.1.1 on 2018-09-26 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('numero_compte', models.PositiveIntegerField(verbose_name='Numéro du compte')),
                ('solde', models.PositiveIntegerField()),
                ('date_expiration', models.DateTimeField(verbose_name="Date d'expiration")),
                ('actif', models.BooleanField(default=True, verbose_name='En activité')),
            ],
            options={
                'verbose_name': 'Compte',
            },
        ),
        migrations.CreateModel(
            name='CompteAlpha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietaire', models.CharField(default='e-pounds Corporation', max_length=100, verbose_name='Propriétaire du compte')),
                ('solde', models.PositiveIntegerField(default=1000000000000, verbose_name='Solde e-pounds')),
            ],
            options={
                'verbose_name': 'Compte Alpha',
                'verbose_name_plural': 'Compte Alpha',
            },
        ),
        migrations.CreateModel(
            name='CompteBeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietaire', models.CharField(default='e-pounds Corporation', max_length=100, verbose_name='Propriétaire du compte')),
                ('solde', models.PositiveIntegerField(default=1000000000000, verbose_name='Solde e-pounds')),
            ],
            options={
                'verbose_name': 'Compte Bêta',
                'verbose_name_plural': 'Compte Bêta',
            },
        ),
        migrations.CreateModel(
            name='CompteGrenier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietaire', models.CharField(default='e-pounds Corporation', max_length=100, verbose_name='Propriétaire du compte')),
                ('solde', models.PositiveIntegerField(default=0, verbose_name='Solde e-pounds')),
            ],
            options={
                'verbose_name': 'Compte Grenier',
                'verbose_name_plural': 'Compte Grenier',
            },
        ),
        migrations.CreateModel(
            name='CompteBusiness',
            fields=[
                ('compte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compte.Compte')),
                ('taux_contribution', models.PositiveIntegerField(default=5, editable=False, verbose_name='Taux de contibution mensuel')),
                ('taux_reconversion', models.PositiveIntegerField(default=70, editable=False, verbose_name='Taux de reconversion')),
            ],
            options={
                'verbose_name': 'Business',
            },
            bases=('compte.compte',),
        ),
        migrations.CreateModel(
            name='CompteConsommateur',
            fields=[
                ('compte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compte.Compte')),
                ('taux_gain', models.PositiveIntegerField(default=50, editable=False, verbose_name="Taux d'intérêt")),
                ('taux_perte', models.PositiveIntegerField(default=40, editable=False, verbose_name='Taux de reconversion')),
                ('taux_fonte_mensuel', models.PositiveIntegerField(default=2, editable=False, verbose_name='Taux de fonte mensuel')),
            ],
            options={
                'verbose_name': 'Consommateur',
            },
            bases=('compte.compte',),
        ),
        migrations.CreateModel(
            name='CompteEntrepriseCommerciale',
            fields=[
                ('compte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compte.Compte')),
                ('credit', models.PositiveIntegerField(verbose_name='Credit')),
                ('taux_rembourssement', models.PositiveIntegerField(default=0, verbose_name="Taux d'intérêt")),
                ('compte_business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='compte.CompteBusiness', verbose_name='Compte Business')),
                ('compte_consommateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='compte.CompteConsommateur', verbose_name='Compte Consommateur')),
            ],
            options={
                'verbose_name': 'Entreprise Commerciale',
            },
            bases=('compte.compte',),
        ),
        migrations.CreateModel(
            name='CompteTrader',
            fields=[
                ('compte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compte.Compte')),
                ('taux_gain', models.PositiveIntegerField(default=10, editable=False, verbose_name="Taux d'intérêt")),
            ],
            options={
                'verbose_name': 'Trader',
            },
            bases=('compte.compte',),
        ),
        migrations.AddField(
            model_name='compte',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_compte.compte_set+', to='contenttypes.ContentType'),
        ),
    ]
