# Generated by Django 2.1.1 on 2018-09-28 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comptebusiness',
            options={'verbose_name': 'Compte Achat'},
        ),
        migrations.AlterModelOptions(
            name='compteconsommateur',
            options={'verbose_name': 'Compte Consommateur'},
        ),
        migrations.AlterModelOptions(
            name='comptetrader',
            options={'verbose_name': 'Compte Trader'},
        ),
        migrations.AlterField(
            model_name='compteentreprisecommerciale',
            name='compte_business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='compte.CompteBusiness', verbose_name='Compte Vente'),
        ),
        migrations.AlterField(
            model_name='compteentreprisecommerciale',
            name='compte_consommateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='compte.CompteConsommateur', verbose_name='Compte Achat'),
        ),
    ]
