# Generated by Django 2.1.1 on 2018-09-30 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_auto_20180928_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 23, 19, 38, 588167), verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='compte',
            name='solde',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
