# Generated by Django 2.1.1 on 2018-10-01 00:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_auto_20180930_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 0, 24, 49, 346485), verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='compteentreprisecommerciale',
            name='compte_business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compteVente_vers_parent', to='compte.CompteBusiness', verbose_name='Compte Vente'),
        ),
        migrations.AlterField(
            model_name='compteentreprisecommerciale',
            name='compte_consommateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compteConsommateur_vers_parent', to='compte.CompteConsommateur', verbose_name='Compte Achat'),
        ),
    ]
