# Generated by Django 2.1.1 on 2018-09-30 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0007_auto_20181001_0137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comptebusiness',
            options={'verbose_name': 'Compte Vente'},
        ),
        migrations.AlterModelOptions(
            name='compteentreprisecommerciale',
            options={'verbose_name': 'Compte Entreprise Commerciale'},
        ),
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 23, 15, 47, 46749), verbose_name="Date d'expiration"),
        ),
    ]
