# Generated by Django 2.1.1 on 2018-10-01 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0008_auto_20180930_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 4, 11, 40, 830100), verbose_name="Date d'expiration"),
        ),
    ]
