# Generated by Django 2.1.1 on 2018-10-04 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0009_auto_20181001_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 23, 0, 56, 4, 776615), verbose_name="Date d'expiration"),
        ),
    ]
