# Generated by Django 2.1.1 on 2018-10-05 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0010_auto_20181004_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 20, 1, 18, 264040), verbose_name="Date d'expiration"),
        ),
    ]
