# Generated by Django 2.1.1 on 2018-10-05 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0011_auto_20181005_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 20, 6, 55, 841714), verbose_name="Date d'expiration"),
        ),
    ]
