# Generated by Django 2.1.1 on 2018-10-06 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0012_auto_20181005_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 11, 17, 8, 290700), verbose_name="Date d'expiration"),
        ),
    ]
