# Generated by Django 2.1.1 on 2018-10-06 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0013_auto_20181006_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 11, 36, 27, 984320), verbose_name="Date d'expiration"),
        ),
    ]
