# Generated by Django 2.1.1 on 2018-10-06 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0014_auto_20181006_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 14, 17, 45, 57565), verbose_name="Date d'expiration"),
        ),
    ]
