# Generated by Django 2.1.1 on 2018-10-06 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0022_auto_20181006_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 16, 21, 35, 360076), verbose_name="Date d'expiration"),
        ),
    ]
