# Generated by Django 2.1.1 on 2018-10-14 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0026_auto_20181014_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 12, 21, 29, 779361), verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='comptebusiness',
            name='taux_contribution',
            field=models.FloatField(default=0.05, editable=False, verbose_name='Taux de contibution mensuel'),
        ),
        migrations.AlterField(
            model_name='comptebusiness',
            name='taux_reconversion',
            field=models.FloatField(default=0.7, editable=False, verbose_name='Taux de reconversion'),
        ),
        migrations.AlterField(
            model_name='compteconsommateur',
            name='taux_gain',
            field=models.FloatField(default=1.5, editable=False, verbose_name="Taux d'intérêt"),
        ),
        migrations.AlterField(
            model_name='compteconsommateur',
            name='taux_perte',
            field=models.FloatField(default=0.6, editable=False, verbose_name='Taux de reconversion'),
        ),
        migrations.AlterField(
            model_name='compteentreprisecommerciale',
            name='taux_rembourssement',
            field=models.FloatField(default=0.0, verbose_name="Taux d'intérêt"),
        ),
        migrations.AlterField(
            model_name='comptetrader',
            name='taux_gain',
            field=models.FloatField(default=1.1, editable=False, verbose_name="Taux d'intérêt"),
        ),
    ]
