# Generated by Django 2.1.1 on 2018-10-14 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0027_auto_20181014_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 12, 53, 38, 97364), verbose_name="Date d'expiration"),
        ),
    ]
