# Generated by Django 2.1.1 on 2018-10-17 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0028_auto_20181014_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 14, 9, 18, 433395), verbose_name="Date d'expiration"),
        ),
    ]
