# Generated by Django 2.1.1 on 2018-10-17 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0031_auto_20181017_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 23, 13, 8, 182669), verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='comptebusiness',
            name='taux_contribution',
            field=models.PositiveIntegerField(default=5, editable=False, verbose_name='Taux de contibution mensuel'),
        ),
        migrations.AlterField(
            model_name='comptebusiness',
            name='taux_reconversion',
            field=models.PositiveIntegerField(default=70, editable=False, verbose_name='Taux de reconversion'),
        ),
        migrations.AlterField(
            model_name='compteconsommateur',
            name='taux_gain',
            field=models.PositiveIntegerField(default=50, editable=False, verbose_name="Taux d'intérêt"),
        ),
        migrations.AlterField(
            model_name='compteconsommateur',
            name='taux_perte',
            field=models.PositiveIntegerField(default=40, editable=False, verbose_name='Taux de reconversion'),
        ),
        migrations.AlterField(
            model_name='compteentreprisecommerciale',
            name='taux_rembourssement',
            field=models.PositiveIntegerField(default=0, verbose_name="Taux d'intérêt"),
        ),
    ]
