# Generated by Django 2.1.1 on 2018-10-17 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0032_auto_20181017_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compteconsommateur',
            name='taux_fonte_mensuel',
        ),
        migrations.RemoveField(
            model_name='compteconsommateur',
            name='taux_gain',
        ),
        migrations.RemoveField(
            model_name='compteconsommateur',
            name='taux_perte',
        ),
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 23, 29, 16, 749464), verbose_name="Date d'expiration"),
        ),
    ]
