# Generated by Django 2.1.1 on 2018-10-18 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0033_auto_20181017_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comptebusiness',
            name='taux_contribution',
        ),
        migrations.RemoveField(
            model_name='comptebusiness',
            name='taux_reconversion',
        ),
        migrations.RemoveField(
            model_name='compteentreprisecommerciale',
            name='taux_rembourssement',
        ),
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 2, 16, 8, 200986), verbose_name="Date d'expiration"),
        ),
    ]
