# Generated by Django 2.1.1 on 2018-10-18 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0035_auto_20181018_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 16, 14, 48, 768088), verbose_name="Date d'expiration"),
        ),
    ]
