# Generated by Django 2.1.1 on 2018-10-18 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0036_auto_20181018_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 15, 9, 4, 759095), verbose_name="Date d'expiration"),
        ),
    ]
