# Generated by Django 2.1.1 on 2018-10-27 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0037_auto_20181018_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptegrenier',
            name='fonte',
            field=models.PositiveIntegerField(null=True, verbose_name='Fonte'),
        ),
        migrations.AddField(
            model_name='comptegrenier',
            name='prelevement_reconversion',
            field=models.PositiveIntegerField(null=True, verbose_name='Prélevement sur Reconversion'),
        ),
        migrations.AddField(
            model_name='comptegrenier',
            name='prelevement_vendeur',
            field=models.PositiveIntegerField(null=True, verbose_name='Prélevement sur Reconversion'),
        ),
        migrations.AddField(
            model_name='comptegrenier',
            name='total_bonification',
            field=models.PositiveIntegerField(null=True, verbose_name='Création Monétaire'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 11, 21, 57, 142665), verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='comptegrenier',
            name='solde',
            field=models.PositiveIntegerField(default=0, verbose_name='Destruction Monaitaire'),
        ),
    ]
