# Generated by Django 2.1.1 on 2018-10-27 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0038_auto_20181027_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptegrenier',
            name='recette',
            field=models.PositiveIntegerField(default=0, verbose_name='Destruction Monaitaire'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 11, 33, 49, 284076), verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='comptegrenier',
            name='solde',
            field=models.PositiveIntegerField(null=True, verbose_name='Solde'),
        ),
    ]
