# Generated by Django 2.1.1 on 2018-10-27 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0039_auto_20181027_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 11, 35, 5, 323853), verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='comptegrenier',
            name='prelevement_vendeur',
            field=models.PositiveIntegerField(null=True, verbose_name='Prélevement sur Vendeur'),
        ),
    ]
