# Generated by Django 2.1.1 on 2018-10-27 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0040_auto_20181027_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comptegrenier',
            name='proprietaire',
        ),
        migrations.RemoveField(
            model_name='comptegrenier',
            name='solde',
        ),
        migrations.RemoveField(
            model_name='comptegrenier',
            name='total_bonification',
        ),
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 12, 7, 6, 217498), verbose_name="Date d'expiration"),
        ),
    ]
