# Generated by Django 2.1.1 on 2018-10-27 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0041_auto_20181027_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 19, 54, 12, 267294), verbose_name="Date d'expiration"),
        ),
    ]
