# Generated by Django 2.1.2 on 2018-10-31 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0042_auto_20181027_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 11, 6, 21, 29421), verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='comptealpha',
            name='solde',
            field=models.PositiveIntegerField(default=10000000, verbose_name='Solde e-pounds'),
        ),
        migrations.AlterField(
            model_name='comptebeta',
            name='solde',
            field=models.PositiveIntegerField(default=10000000, verbose_name='Solde e-pounds'),
        ),
    ]
