# Generated by Django 2.1.2 on 2018-11-26 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0043_auto_20181031_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 13, 24, 2, 341178), verbose_name="Date d'expiration"),
        ),
    ]
