# Generated by Django 2.1.2 on 2018-12-13 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0045_auto_20181213_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 21, 50, 14, 687627), verbose_name="Date d'expiration"),
        ),
    ]
