# Generated by Django 2.1.2 on 2018-12-13 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0046_auto_20181213_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 21, 59, 32, 578393), verbose_name="Date d'expiration"),
        ),
    ]
