# Generated by Django 2.1.2 on 2019-01-21 14:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0049_auto_20190119_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 14, 3, 55, 610023), verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='compteentreprisecommerciale',
            name='compte_business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vente_vers_entreprise', to='compte.CompteBusiness', verbose_name='Compte Vente'),
        ),
        migrations.AlterField(
            model_name='compteentreprisecommerciale',
            name='compte_consommateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conso_vers_entreprise', to='compte.CompteConsommateur', verbose_name='Compte Achat'),
        ),
        migrations.AlterField(
            model_name='compteentreprisecommerciale',
            name='credit',
            field=models.PositiveIntegerField(default=0, verbose_name='Credit'),
        ),
    ]
