# Generated by Django 2.1.2 on 2019-03-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0053_auto_20190223_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteconsommateur',
            name='depense_epound_mensuel',
            field=models.PositiveIntegerField(default=0, verbose_name='Depense mensuel'),
        ),
    ]
